update readme fetch integration docs
fetchoracle/usingfetch pull request #10
Opened 2024-05-13 03:07 UTC by jensendarren

2024-05-14 02:15 UTC, merged

2024-09-21 00:05 UTC, KolomboPulse commented on README.md
> -      bytes32 _plsQueryId = keccak256(abi.encode("SpotPrice", abi.encode("pls", "usd")));
pls

2024-09-21 00:05 UTC, KolomboPulse commented on README.md
> +      bytes32 _plsQueryId = keccak256(abi.encode("SpotPrice", abi.encode("llpls", "usd")));
llpls

2024-09-21 00:05 UTC, KolomboPulse commented on README.md
> -mainnet: 0x6f390b99201bb43A05757019efe9C99651e04584
mainnet: 0x6f390b99201bb43A05757019efe9C99651e04584

2024-09-21 00:05 UTC, KolomboPulse commented on README.md
> -testnet: 0x252eC80dEa7F3eD0CC57e0f1112d6f56Ae9523fb
testnet: 0x252eC80dEa7F3eD0CC57e0f1112d6f56Ae9523fb

2024-09-21 00:05 UTC, KolomboPulse commented on README.md
> +* mainnet: `0x23716E2dCC327429253335E4646dEbaD1Ac0E57c`
* mainnet: `0x23716E2dCC327429253335E4646dEbaD1Ac0E57c`

2024-09-21 00:05 UTC, KolomboPulse commented on README.md
> +* testnet: `0x252eC80dEa7F3eD0CC57e0f1112d6f56Ae9523fb`
* testnet: `0x252eC80dEa7F3eD0CC57e0f1112d6f56Ae9523fb`

2024-09-21 00:05 UTC, KolomboPulse commented on README.md
> -# Implementing using Fetch
# Implementing using Fetch

2024-09-21 00:05 UTC, KolomboPulse commented on README.md
> -See our documentation for implementing usingFetch [here.](https://docs.fetchoracle.com/fetch/getting-data/introduction)
See our documentation for implementing usingFetch [here.](https://docs.fetchoracle.com/fetch/getting-data/introduction)

2024-09-21 00:07 UTC, KolomboPulse approved these changes

2024-09-23 02:41 UTC, darren-ll commented
Hi @KolomboPulse 👋 - thank you for your earlier comments on this PR. Can you help to share a little more context please so that I may help you?

2024-09-23 07:59 UTC, KolomboPulse commented on README.md
> -      bytes32 _plsQueryId = keccak256(abi.encode("SpotPrice", abi.encode("pls", "usd")));
pls

2024-09-23 13:25 UTC, KolomboPulse reviewed
update readme fetch integration docs #10

2024-09-23 13:25 UTC, KolomboPulse commented on README.md
> -See our documentation for implementing usingFetch [here.](https://docs.fetchoracle.com/fetch/getting-data/introduction)
See our documentation for implementing usingFetch [here.](https://docs.fetchoracle.com/fetch/getting-data/introduction)

2024-09-23 13:39 UTC, KolomboPulse reviewed
update readme fetch integration docs #10

2024-09-23 14:30 UTC, KolomboPulse requested changes

2024-09-23 14:30 UTC, KolomboPulse commented on README.md
> -# Implementing using Fetch
# Implementing using Fetch